---
- name: Testing andrewrothstein.dive
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'dive --version'
      ansible.builtin.command: dive --version
      changed_when: false
      register: dive_test_output
    - name: Output from 'dive --version'
      ansible.builtin.debug:
        msg: '{{ dive_test_output.stdout }}'
