---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ dive_install_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ dive_install_exe }}'
  changed_when: false
  register: dive_binary
- name: Downloading and installing dive
  when: not dive_binary.stat.exists
  block:
    - name: Downloading {{ dive_url }} to {{ dive_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ dive_url }}'
        dest: '{{ dive_tmp_archive }}'
        mode: '644'
        checksum: '{{ dive_checksum }}'
    - name: Mkdir {{ dive_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dive_install_dir }}'
        mode: '755'
        state: directory
    - name: Unarchive
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ dive_tmp_archive }}'
        dest: '{{ dive_install_dir }}'
        creates: '{{ dive_install_dir }}/dive'
  always:
    - name: Rm {{ dive_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ dive_tmp_archive }}'
        state: absent
- name: Linking {{ dive_link }} to {{ dive_install_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ dive_install_exe }}'
    dest: '{{ dive_link }}'
    state: link
